import anvil.server

# This is a server module. It runs on the Anvil server,
# rather than in the user's browser.
#
# To allow anvil.server.call() to call functions here, we mark
# them with @anvil.server.callable.
# Here is an example - you can replace it with your own:
#
# @anvil.server.callable
# def say_hello(name):
#   print("Hello, " + name + "!")
#   return 42
#
import sys, os, re
import anvil.server  # Ključno za Anvil

EXACT = [
  ("pevac",               "kokot"),
  ("sutra",               "śutra"),
  ("čovečanstvo",         "čovječanstvo"),
  ("detinjstvu",          "djetinjstvu"),
  ("detinjstva",          "djetinjstva"),
  ("detinjstvo",          "djetinjstvo"),
  ("neuspesima",          "neuspjesima"),
  ("neuspeha",            "neuspjeha"),
  ("neuspehe",            "neuspjehe"),
  ("neuspesi",            "neuspjesi"),
  ("neuspeh",             "neuspjeh"),
  ("zabeležili",          "zabilježili"),
  ("zabeležio",           "zabilježio"),
  ("zabeležen",           "zabilježen"),
  ("zabeleže",            "zabilježe"),
  ("poverljivu",          "povjerljivu"),
  ("poverljiv",           "povjerljiv"),
  ("nameštanja",          "namještanja"),
  ("nameštanje",          "namještanje"),
  ("bezbednosti",         "bezbjednosti"),
  ("poslednjeg",          "posljednjeg"),
  ("poslednje",           "posljednje"),
  ("dodeljivanja",        "dodjeljivanja"),
  ("dodeljena",           "dodijeljena"),
  ("dodele",              "dodjele"),
  ("dodeliti",            "dodijeliti"),
  ("dodelio",             "dodijelio"),
  ("zahtevala",           "zahtijevala"),
  ("obletevši",           "obletjevši"),
  ("obavešteno",          "obavješteno"),
  ("dragocena",           "dragocjena"),
  ("dragoceno",           "dragocjeno"),
  ("dragocen",            "dragocjen"),
  ("posleratni",          "poslijeratni"),
  ("posleratnog",         "poslijeratnog"),
  ("sledeće",             "sljedeće"),
  ("sledeća",             "sljedeća"),
  ("pobedile",            "pobijedile"),
  ("pobedili",            "pobijedili"),
  ("verovatno",           "vjerovatno"),
  ("verovali",            "vjerovali"),
  ("verovala",            "vjerovala"),
  ("pretnji",             "prijetnji"),
  ("pretnje",             "prijetnje"),
  ("pretnja",             "prijetnja"),
  ("naslednika",          "nasljednika"),
  ("doneli",              "donijeli"),
  ("zamenila",            "zamijenila"),
  ("smenjen",             "smijenjen"),
  ("smeniti",             "smijeniti"),
  ("smene",               "smjene"),
  ("poletela",            "poletjela"),
  ("proletela",           "proletjela"),
  ("proleteo",            "proletio"),
  ("uzletela",            "uzletjela"),
  ("letele",              "letjele"),
  ("leteo",               "letio"),
  ("sletanje",            "slijetanje"),
  ("sletanja",            "slijetanja"),
  ("sletanjem",           "slijetanjem"),
  ("sletanju",            "slijetanju"),
  ("sleteli",             "sletjeli"),
  ("sletela",             "sletjela"),
  ("sleteti",             "sletjeti"),
  ("sleteo",              "sletio"),
  ("slete",               "slijete"),
  ("sleti",               "slijeti"),
  ("pobede",              "pobjede"),
  ("podeljene",           "podijeljene"),
  ("podeljena",           "podijeljena"),
  ("podeljen",            "podijeljen"),
  ("podele",              "podjele"),
  ("nerešeni",            "neriješeni"),
    ("razrešen",            "razriješen"),
    ("reše",                "riješe"),
    ("predela",             "predjela"),
    ("posedovanja",         "posjedovanja"),
    ("izvestio",            "izvijestio"),
    ("vesti",               "vijesti"),
    ("dece",                "djece"),
    ("zamenu",              "zamjenu"),
    ("odela",               "odijela"),
    ("odelo",               "odijelo"),
    ("odeća",               "odjeća"),
    ("deo",                 "dio"),
    ("neuspešno",           "neuspješno"),
    ("predsednika",         "predsjednika"),
    ("pobedila",            "pobijedila"),
    ("pobedio",             "pobijedio"),
    ("primene",             "primjene"),
    ("primena",             "primjena"),
    ("primer",              "primjer"),
    ("celina",              "cjelina"),
    ("nedelje",             "nedjelje"),
    ("obletela",            "obletjela"),
    ("volelo",              "voljelo"),
    ("volela",              "voljela"),
    ("povređeno",           "povrijeđeno"),
    ("svedočanstvo",        "svjedočanstvo"),
    ("svedočenje",          "svjedočenje"),
    ("nasledništvo",        "nasljedništvo"),
    ("naslednica",          "nasljednica"),
    ("naslednik",           "nasljednik"),
    ("celovitost",          "cjelovitost"),
    ("celovito",            "cjelovito"),
    ("celovit",             "cjelovit"),
    ("vrednost",            "vrijednost"),
    ("vrednovanje",         "vrjednovanje"),
    ("vredan",              "vrijedan"),
    ("verodostojan",        "vjerodostojan"),
    ("verovati",            "vjerovati"),
    ("vernost",             "vjernost"),
    ("verno",               "vjerno"),
    ("veran",               "vjeran"),
    ("bezbednim",           "bezbjednim"),
    ("bezbedna",            "bezbjedna"),
    ("bezbedno",            "bezbjedno"),
    ("rešenja",             "rješenja"),
    ("rešenje",             "rješenje"),
    ("predeo",              "predio"),
    ("zamena",              "zamjena"),
    ("smena",               "smjena"),
    ("promenio",            "promijenio"),
    ("promenila",           "promijenila"),
    ("promenilo",           "promijenilo"),
    ("promene",             "promjene"),
    ("promena",             "promjena"),
    ("izmenio",             "izmijenio"),
    ("zamenio",             "zamijenio"),
    ("menjao",              "mijenjao"),
    ("prisetiti",           "prisjetiti"),
    ("prisećanje",          "prisjećanje"),
    ("neravnomerno",        "neravnomjerno"),
    ("bezbednost",          "bezbjednost"),
    ("predsedništvo",       "predsjedništvo"),
    ("posedovanje",         "posjedovanje"),
    ("povređivanje",        "povrjeđivanje"),
    ("povređen",            "povrijeđen"),
    ("poslepodne",          "poslijepodne"),
    ("poslediplomski",      "posljediplomski"),
    ("posledično",          "posljedično"),
    ("razumevanja",         "razumijevanja"),
    ("unapredite",          "unaprijedite"),
    ("izbegavajte",         "izbjegavajte"),
    ("posećujete",          "posjećujete"),
    ("razgovetno",          "razgovjetno"),
    ("razumeti",            "razumjeti"),
    ("preterano",           "pretjerano"),
    ("promenite",           "promijenite"),
    ("vrednosti",           "vrijednosti"),
    ("smernice",            "smjernice"),
    ("veštine",             "vještine"),
    ("uspešno",             "uspješno"),
    ("sledeći",             "sljedeći"),
    ("umesto",              "umjesto"),
    ("namesto",             "namjesto"),
    ("zahtevati",           "zahtijevati"),
    ("zahteva",             "zahtijeva"),
    ("saveta",              "savjeta"),
    ("saveti",              "savjeti"),
    ("dečaštvo",            "dječaštvo"),
    ("dečija",              "dječija"),
    ("smešan",              "smiješan"),
    ("nepoverenje",         "nepovjerenje"),
    ("nepoverljivo",        "nepovjerljivo"),
    ("nepoverljiv",         "nepovjerljiv"),
    ("poverovati",          "povjerovati"),
    ("poverenje",           "povjerenje"),
    ("devojka",             "djevojka"),
    ("namera",              "namjera"),
    ("nasmešiti",           "nasmiješiti"),
    ("pobediti",            "pobijediti"),
    ("pobeditelj",          "pobjeditelj"),
    ("pobednik",            "pobjednik"),
    ("pobeda",              "pobjeda"),
    ("doneti",              "donijeti"),
    ("grešiti",             "griješiti"),
    ("izmenjivač",          "izmjenjivač"),
    ("menjačnica",          "mjenjačnica"),
    ("menjati",             "mijenjati"),
    ("bežanija",            "bježanija"),
    ("bežati",              "bježati"),
    ("cediljka",            "cjediljka"),
    ("ceđenje",             "cijeđenje"),
    ("cediti",              "cijediti"),
    ("letovanje",           "ljetovanje"),
    ("letovalište",         "ljetovalište"),
    ("odletanje",           "odlijetanje"),
    ("odleteti",            "odletjeti"),
    ("letenje",             "letjenje"),
    ("leteti",              "letjeti"),
    ("odmeren",             "odmjeren"),
    ("odmeriti",            "odmjeriti"),
    ("izmeriti",            "izmjeriti"),
    ("izmeriv",             "izmjeriv"),
    ("merilo",              "mjerilo"),
    ("meriti",              "mjeriti"),
    ("sedeti",              "sjedjeti"),
    ("terati",              "tjerati"),
    ("naterati",            "natjerati"),
    ("videti",              "vidjeti"),
    ("voleti",              "voljeti"),
    ("pevačica",            "pjevačica"),
    ("pevačko",             "pjevačko"),
    ("pevač",               "pjevač"),
    ("pevati",              "pjevati"),
    ("nerešeno",            "neriješeno"),
    ("nerešiv",             "nerješiv"),
    ("odrešen",             "odriješen"),
    ("rešiti",              "riješiti"),
    ("podeliti",            "podijeliti"),
    ("deljenje",            "dijeljenje"),
    ("delimično",           "djelimično"),
    ("deliti",              "dijeliti"),
    ("podela",              "podjela"),
    ("gnezdo",              "gnijezdo"),
    ("kolenica",            "koljenica"),
    ("kolenaст",            "koljenast"),
    ("koleno",              "koljeno"),
    ("cenovnik",            "cjenovnik"),
    ("celoživotni",         "cjeloživotni"),
    ("cenjen",              "cijenjen"),
    ("zvezdica",            "zvjezdica"),
    ("zvezdani",            "zvjezdani"),
    ("zvezda",              "zvijezda"),
    ("svetlo",              "svijetlo"),
    ("osvetljenje",         "osvjetljenje"),
    ("osvetliti",           "osvijetliti"),
    ("svetlucati",          "svjetlucati"),
    ("sveća",               "svijeća"),
    ("mesečina",            "mjesečina"),
    ("mesečni",             "mjesečni"),
    ("mesečar",             "mjesečar"),
    ("mestimično",          "mjestimično"),
    ("mesec",               "mjesec"),
    ("osvestiti",           "osvijestiti"),
    ("osvešćenost",         "osvješćenost"),
    ("osvetljenost",        "osvjetljenost"),
    ("obaveštenje",         "obavještenje"),
    ("obavestiti",          "obavijestiti"),
    ("svest",               "svijest"),
    ("pesak",               "pijesak"),
    ("uspešan",             "uspješan"),
    ("uspeh",               "uspjeh"),
    ("vetrenjača",          "vjetrenjača"),
    ("vetar",               "vjetar"),
    ("dečak",               "dječak"),
    ("dečji",               "dječiji"),
    ("dete",                "dijete"),
    ("deca",                "djeca"),
    ("slepi",               "slijepi"),
    ("seno",                "sijeno"),
    ("sena",                "sjena"),
    ("lekovito",            "ljekovito"),
    ("lekarija",            "ljekarija"),
    ("lekarka",             "ljekarka"),
    ("lečenje",             "liječenje"),
    ("izlečiti",            "izliječiti"),
    ("lekar",               "ljekar"),
    ("lepo",                "lijepo"),
    ("lepota",              "ljepota"),
    ("telesni",             "tjelesni"),
    ("telo",                "tijelo"),
    ("breg",                "brijeg"),
    ("cvetanje",            "cvjetanje"),
    ("cvetić",              "cvjetić"),
    ("cvećar",              "cvjećar"),
    ("cvet",                "cvijet"),
    ("snežan",              "sniježan"),
    ("snežni",              "snježni"),
    ("sneg",                "snijeg"),
    ("zver",                "zvijer"),
    ("gnev",                "gnijev"),
    ("bedan",               "bijedan"),
    ("bedni",               "bijedni"),
    ("beda",                "bijeda"),
    ("zenica",              "zjenica"),
    ("mešalica",            "mješalica"),
    ("mešavina",            "mješavina"),
    ("mešati",              "miješati"),
    ("mera",                "mjera"),
    ("reka",                "rijeka"),
    ("mleko",               "mlijeko"),
    ("leto",                "ljeto"),
    ("cena",                "cijena"),
    ("hleb",                "hljeb"),
    ("vera",                "vjera"),
    ("vreme",               "vrijeme"),
    ("namestiti",           "namjestiti"),
    ("mesto",               "mjesto"),
    ("savet",               "savjet"),
    ("zauvek",              "zauvijek"),
    ("uvek",                "uvijek"),
    ("rečnik",              "rječnik"),
    ("rečica",              "rječica"),
    ("reči",                "riječi"),
    ("pena",                "pjena"),
    ("belo",                "bijelo"),
    ("bela",                "bijela"),
    ("celi",                "cijeli"),
    ("uspeo",               "uspio"),
    ("crep",                "crijep"),
    ("crevo",               "crijevo"),
    ("cev",                 "cijev"),
    ("ceo",                 "cio"),
    ("nedeljni",            "nedjeljni"),
    ("nedelja",             "nedjelja"),
    ("ponedeljkom",         "ponedjeljkom"),
    ("ponedeljak",          "ponedjeljak"),
    ("negde",               "negdje"),
    ("ovde",                "ovdje"),
    ("osmehivati",          "osmjehivati"),
    ("osmehnuti",           "osmjehnuti"),
    ("osmeh",               "osmijeh"),
    ("poslednji",           "posljednji"),
    ("posledica",           "posljedica"),
    ("posednik",            "posjednik"),
    ("posed",               "posjed"),
    ("posle",               "poslije"),
    ("povest",              "povijest"),
    ("delokrug",            "djelokrug"),
    ("delo",                "djelo"),
    ("ogrev",               "ogrijev"),
    ("pešačenje",           "pješačenje"),
    ("pešadija",            "pješadija"),
    ("pešački",             "pješački"),
    ("pešak",               "pješak"),
    ("predsednica",         "predsjednica"),
    ("predsednik",          "predsjednik"),
    ("obesiti",             "objesiti"),
    ("obešenjak",           "obješenjak"),
    ("grehota",             "grjehota"),
    ("greh",                "grijeh"),
    ("blesnuti",            "bljesnuti"),
    ("blesak",              "bljesak"),
    ("neosetljiv",          "neosjetljiv"),
    ("osetljiv",            "osjetljiv"),
    ("osvežavanje",         "osvježavanje"),
    ("izvetriti",           "izvjetriti"),
    ("nežno",               "nježno"),
    ("besan",               "bijesan"),
    ("bes",                 "bijes"),
    ("vek",                 "vijek"),
    ("lek",                 "lijek"),
    ("svet",                "svijet"),
    ("smejati",             "smijati"),
    # ── Yates article additions ──
    ("cela",                "cijela"),
    ("celim",               "cijelim"),
    ("celog",               "cijelog"),
    ("celu",                "cijelu"),
    ("cenila",              "cijenila"),
    ("delimična",           "djelimična"),
    ("deteta",              "djeteta"),
    ("detetom",             "djetetom"),
    ("devojke",             "djevojke"),
    ("devojku",             "djevojku"),
    ("devojčica",           "djevojčica"),
    ("devojčice",           "djevojčice"),
    ("devojčicu",           "djevojčicu"),
    ("hleba",               "hljeba"),
    ("izbegne",             "izbjegne"),
    ("izbegnu",             "izbjegnu"),
    ("izmenama",            "izmjenama"),
    ("izmene",              "izmjene"),
    ("izmenjene",           "izmijenjene"),
    ("izmenjenim",          "izmijenjenim"),
    ("lepe",                "lijepe"),
    ("lepote",              "ljepote"),
    ("lepotica",            "ljepotica"),
    ("lepotici",            "ljepotici"),
    ("lepoticom",           "ljepoticom"),
    ("lekara",              "ljekara"),
    ("lekare",              "ljekare"),
    ("lekari",              "ljekari"),
    ("leka",                "lijeka"),
    ("leku",                "lijeku"),
    ("leta",                "ljeta"),
    ("mere",                "mjere"),
    ("meri",                "mjeri"),
    ("meru",                "mjeru"),
    ("meseca",              "mjeseca"),
    ("meseci",              "mjeseci"),
    ("nameštaj",            "namještaj"),
    ("nedelju",             "nedjelju"),
    ("neuspeli",            "neuspjeli"),
    ("neuspešna",           "neuspješna"),
    ("obavestila",          "obavijestila"),
    ("obavestio",           "obavijestio"),
    ("obavešteni",          "obavješteni"),
    ("obaveštenja",         "obavještenja"),
    ("osmehom",             "osmijehom"),
    ("pobednika",           "pobjednika"),
    ("pobedonosnog",        "pobjedonosnog"),
    ("podeljenosti",        "podijeljenos ti"),
    ("posedima",            "posjedima"),
    ("posednjem",           "posjednjem"),
    ("posedovala",          "posjedovala"),
    ("posedovali",          "posjedovali"),
    ("posedovao",           "posjedovao"),
    ("poseduje",            "posjeduje"),
    ("poslednja",           "posljednja"),
    ("poslednjem",          "posljednjem"),
    ("poslednjim",          "posljednjim"),
    ("poslednjoj",          "posljednjoj"),
    ("poslednju",           "posljednju"),
    ("posleratne",          "poslijeratne"),
    ("posleratnih",         "poslijeratnih"),
    ("posleratnim",         "poslijeratnim"),
    ("posleratnom",         "poslijeratnom"),
    ("potpredsednici",      "potpredsjednici"),
    ("potpredsednika",      "potpredsjednika"),
    ("potpredsednik",       "potpredsjednik"),
    ("predsedavala",        "predsjedavala"),
    ("predsednikom",        "predsjednikom"),
    ("predsedniku",         "predsjedniku"),
    ("predsedništva",       "predsjedništva"),
    ("predsedništvu",       "predsjedništvu"),
    ("premešten",           "premješten"),
    ("smenu",               "smjenu"),
    ("smeni",               "smjeni"),
    ("svesni",              "svjesni"),
    ("veka",                "vijeka"),
    ("veku",                "vijeku"),
    ("verila",              "vjerila"),
    ("verna",               "vjerna"),
    ("vernik",              "vjernik"),
    ("vetra",               "vjetra"),
    ("zabeleške",           "zabilješke"),
    ("zamenika",            "zamjenika"),
    ("zamenik",             "zamjenik"),
    ("zamenilo",            "zamijenilo"),
    ("zamenjen",            "zamijenjen"),
    ("zamenjivao",          "zamjenjivao"),
    ("živela",              "živjela"),
    ("živeli",              "živjeli"),
    ("želela",              "željela"),
    ("želeli",              "željeli"),
    ("želeo",               "željeo"),
    ("šestomesečnu",        "šestomjesečnu"),
]

STEMS = [
    ("oseć",    "osjeć"),
    ("seć",     "sjeć"),
    ("pev",     "pjev"),
    ("menjač",  "mjenjač"),
    ("vešt",    "vješt"),
    ("koren",   "korijen"),
    ("belež",   "biljež"),
    ("obelež",  "obiljež"),
    ("zabelež", "zabiljež"),
    ("čovek",   "čovjek"),
    ("letelic", "letjelic"),
    ("namer",   "namjer"),
    ("smenj",   "smjenj"),
    ("delat",   "djelat"),
]


def _wb(word):
    return re.compile(r'(?<![^\W\d_])' + re.escape(word) + r'(?![^\W\d_])', re.UNICODE)

def _stem(stem):
    return re.compile(r'(?<![^\W\d_])(' + re.escape(stem) + r')(\w*)', re.UNICODE | re.IGNORECASE)

_EXACT = [(_wb(e), e, i) for e, i in EXACT]
_STEMS = [(_stem(e), e, i) for e, i in STEMS]


def _apply_exact(text):
    for pat, e, i in _EXACT:
        text = pat.sub(i, text)
        text = _wb(e.capitalize()).sub(i.capitalize(), text)
        text = _wb(e.upper()).sub(i.upper(), text)
    return text

def _apply_stems(text):
    for pat, e, i in _STEMS:
        def _r(m, ije=i):
            s, suf = m.group(1), m.group(2)
            if s.isupper(): return ije.upper() + suf
            if s[0].isupper(): return ije.capitalize() + suf
            return ije + suf
        text = pat.sub(_r, text)
    return text

def replace_words(text):
    return _apply_stems(_apply_exact(text))

def process_file(inp, out):
    if not os.path.isfile(inp):
        print(f"Error: '{inp}' not found."); sys.exit(1)
    with open(inp, encoding="utf-8") as f: text = f.read()
    with open(out, "w", encoding="utf-8") as f: f.write(replace_words(text))
    print(f"Done: '{inp}' -> '{out}'")

# ─────────────────────────────────────────────────────────────────────────────
# GLAVNA ANVIL FUNKCIJA (Ovu funkciju pozivate sa klijenta)
# ─────────────────────────────────────────────────────────────────────────────
@anvil.server.callable
def ijekavizuj_tekst(ulazni_tekst):
    """Prima ekavski tekst sa UI forme, pokreće zamjene i vraća ijekavski tekst."""
    if not ulazni_tekst:
        return ""
    
    # 1. Prvo primijeni EXACT listu
    tekst = _apply_exact(ulazni_tekst)
    
    # 2. Zatim primijeni STEM listu
    konacni_tekst = _apply_stems(tekst)
    
    return konacni_tekst