import anvil.server
import os
import re

EXACT = [
   ('unapređenjima', 'unaprjeđenjima'),
    ('pravovercima', 'pravovjernima'),
    ('unapređenja', 'unaprjeđenja'),
    ('unapređenje', 'unaprjeđenje'),
    ('unapređenju', 'unaprjeđenju'),
    ('pravoverca', 'pravovjernog'),
    ('pravoverce', 'pravovjerne'),
    ('pravoverci', 'pravovjerni'),
    ('pravovercu', 'pravovjernom'),
    ('celinama', 'cjelinama'),
    ('doprineo', 'doprinio'),
    ('pretrpeo', 'pretrpio'),
    ('razboleo', 'razbolio'),
    ('verbalne', 'verbalne'),
    ('verbalne', 'verbalne'),
    ('verzija', 'verzija'),
    ('verzija', 'verzija'),
    ('zamenik', 'zamjenik'),
    ('celima', 'cijelima'),
    ('celina', 'cjelina'),
    ('celine', 'cjeline'),
    ('celini', 'cjelini'),
    ('celinu', 'cjelinu'),
    ('dedama', 'djedovima'),
    ('dedovi', 'djedovi'),
    ('drugde', 'drugdje'),
    ('najpre', 'najprije'),
    ('napred', 'naprijed'),
    ('nemima', 'nijemima'),
    ('rečima', 'riječima'),
    ('svideo', 'svidio'),
    ('uvideo', 'uvidio'),
    ('doneo', 'donio'),
    ('nigde', 'nigdje'),
    ('pevac', 'kokot'),
    ('rekao', 'rekao'),
    ('rekla', 'rekla'),
    ('rečju', 'riječji'),
    ('sreda', 'srijeda'),
    ('svest', 'svijest'),
    ('uspeo', 'uspio'),
    ('uspeo', 'uspio'),
    ('video', 'vidio'),
    ('vreme', 'vrijeme'),
    ('želeo', 'želio'),
    ('žudeo', 'žudio'),
    ('cela', 'cijela'),
    ('cele', 'cijele'),
    ('celi', 'cijeli'),
    ('celo', 'cijelo'),
    ('celu', 'cijelu'),
    ('dece', 'djece'),
    ('dede', 'djedovi'),
    ('dedi', 'djedi'),
    ('dedu', 'djedu'),
    ('dele', 'dijele'),
    ('dete', 'dijete'),
    ('hteo', 'htio'),
    ('leta', 'ljeta'),
    ('nem.', 'njem.'),
    ('nema', 'nijema'),
    ('neme', 'nijeme'),
    ('nemi', 'nijemi'),
    ('nemo', 'nijemo'),
    ('plen', 'plijen'),
    ('reka', 'rijeka'),
    ('reke', 'rijeke'),
    ('reko', 'rijeko'),
    ('reku', 'rijeku'),
    ('reči', 'riječ'),
    ('smeo', 'smio'),
    ('uvek', 'uvijek'),
    ('uvid', 'uvid'),
    ('vera', 'vjera'),
    ('vere', 'vjere'),
    ('veri', 'vjeri'),
    ('veru', 'vjeru'),
    ('vide', 'vide'),
    ('žele', 'žele'),
    ('bes', 'bijes'),
    ('ceo', 'cio'),
    ('ded', 'djed'),
    ('deo', 'dio'),
    ('dev', 'djev'),
    ('dve', 'dvije'),
    ('lek', 'lijek'),
    ('nem', 'nijem'),
    ('obe', 'obje'),
    ('pre', 'prije'),
    ('reč', 'riječ'),
    ('sme', 'smije'),
]

STEMS = [
    ('četvoromeseč', 'četvoromjeseč'),
    ('desetomeseč', 'desetomjeseč'),
    ('devetomeseč', 'devetomjeseč'),
    ('predstavnik', 'predstavnik'),
    ('jednomeseč', 'jednomjeseč'),
    ('pretpostav', 'pretpostav'),
    ('sedmomeseč', 'sedmmjeseč'),
    ('šestomeseč', 'šestomjeseč'),
    ('osmomeseč', 'osmoomjeseč'),
    ('petomeseč', 'petomjeseč'),
    ('podrazume', 'podrazumije'),
    ('presecanj', 'presijecanj'),
    ('presecanj', 'presijecanj'),
    ('bezuspeš', 'bezuspješ'),
    ('celobroj', 'cjelobroj'),
    ('doprinel', 'doprinijel'),
    ('doprinos', 'doprinios'),
    ('dragocen', 'dragocjen'),
    ('dvomeseč', 'dvomjeseč'),
    ('opredeli', 'opredijeli'),
    ('opredelj', 'opredjelj'),
    ('ponedelj', 'ponedjelj'),
    ('potpreds', 'potpredsj'),
    ('potpreds', 'potpredsj'),
    ('predvide', 'predvidje'),
    ('pregreja', 'pregrija'),
    ('pretrpel', 'pretrpjel'),
    ('ravnomer', 'ravnomjern'),
    ('tromeseč', 'tromjeseč'),
    ('verovatn', 'vjerovatn'),
    ('zakasnel', 'zakašnjel'),
    ('zaveštan', 'zavještan'),
    ('delegat', 'delegat'),
    ('delimič', 'djelimič'),
    ('izbegav', 'izbjegav'),
    ('letelic', 'letjelic'),
    ('nadžive', 'nadživje'),
    ('napredn', 'napredn'),
    ('napredo', 'napredo'),
    ('neizbež', 'neizbjež'),
    ('neizmer', 'neizmjer'),
    ('obavest', 'obavijest'),
    ('obavešt', 'obavješt'),
    ('obezbed', 'obezbijed'),
    ('obezbeđ', 'obezbjeđ'),
    ('ocenjiv', 'ocjenjiv'),
    ('odeljak', 'odjeljak'),
    ('osvedoč', 'osvjedoč'),
    ('osvetli', 'osvijetli'),
    ('osvetlj', 'osvjetlj'),
    ('podsmeh', 'podsmjeh'),
    ('pogreši', 'pogriješi'),
    ('poverlj', 'povjerlj'),
    ('povredi', 'povrijedi'),
    ('prebole', 'prebolje'),
    ('predlog', 'prijedlog'),
    ('premest', 'premjest'),
    ('premešt', 'premješt'),
    ('prethod', 'prethod'),
    ('primedb', 'primjedb'),
    ('primeni', 'primijeni'),
    ('primenj', 'primijenj'),
    ('procena', 'procjena'),
    ('procene', 'procjene'),
    ('proceni', 'procijeni'),
    ('procenj', 'procjenj'),
    ('procenu', 'procjenu'),
    ('prosleđ', 'prosljeđ'),
    ('rasejan', 'rasijan'),
    ('razbole', 'razbolje'),
    ('razmenj', 'razmjenj'),
    ('razume', 'razumije'),
    ('telefon', 'telefon'),
    ('umetnik', 'umjetnik'),
    ('unapređ', 'unapređ'),
    ('zabelež', 'zabiljež'),
    ('zahteva', 'zahtijeva'),
    ('zaplena', 'zapljena'),
    ('zaplene', 'zapljene'),
    ('zapleni', 'zaplijeni'),
    ('zaplenu', 'zapljenu'),
    ('bekstv', 'bjekstv'),
    ('decemb', 'decemb'),
    ('dedukt', 'dedukt'),
    ('delima', 'djelima'),
    ('delimi', 'djelimi'),
    ('detalj', 'detalj'),
    ('detinj', 'djetinj'),
    ('dodeli', 'dodijeli'),
    ('dodelj', 'dodjelj'),
    ('dospel', 'dospjel'),
    ('dožive', 'doživje'),
    ('gnezdo', 'gnijezdo'),
    ('izgore', 'izgorje'),
    ('izvesn', 'izvjesn'),
    ('izvest', 'izvijest'),
    ('menjač', 'mjenjač'),
    ('nalepn', 'naljepn'),
    ('namešt', 'namješt'),
    ('nasled', 'naslijed'),
    ('nasmeš', 'nasmiješ'),
    ('nedelj', 'nedjelj'),
    ('nemošć', 'nijemošć'),
    ('neretk', 'nerijetk'),
    ('neuspe', 'neuspje'),
    ('obelež', 'obiljež'),
    ('odeven', 'odjeven'),
    ('pešačk', 'pješačk'),
    ('pobedi', 'pobijedi'),
    ('pobegl', 'pobjegl'),
    ('podela', 'podjela'),
    ('podseć', 'podsjeć'),
    ('porekl', 'porijekl'),
    ('posled', 'posljed'),
    ('posred', 'posred'),
    ('povest', 'povijest'),
    ('povređ', 'povrijeđ'),
    ('predse', 'predsje'),
    ('predst', 'predst'),
    ('predst', 'predst'),
    ('preduz', 'preduz'),
    ('preseć', 'presjeć'),
    ('prevar', 'prevar'),
    ('preživ', 'preživ'),
    ('preživ', 'preživj'),
    ('primen', 'primjen'),
    ('primer', 'primjer'),
    ('proleć', 'proljeć'),
    ('promen', 'promjen'),
    ('prosek', 'prosijek'),
    ('proseč', 'prosječ'),
    ('prosle', 'proslije'),
    ('proter', 'protjer'),
    ('prover', 'provjer'),
    ('razmer', 'razmjer'),
    ('razreš', 'razriješ'),
    ('razume', 'razumje'),
    ('razume', 'razumije'),
    ('reklam', 'reklam'),
    ('rešenj', 'rješenj'),
    ('savest', 'savjest'),
    ('smatra', 'smatra'),
    ('stalež', 'stalež'),
    ('strelj', 'strijelj'),
    ('svetlo', 'svjetlo'),
    ('svetsk', 'svjetsk'),
    ('svugde', 'svugdje'),
    ('unapre', 'unaprije'),
    ('vaspit', 'vaspit'),
    ('verova', 'vjerova'),
    ('vremen', 'vremen'),
    ('zahtev', 'zahtjev'),
    ('zahtev', 'zahtijev'),
    ('zamenj', 'zamjenj'),
    ('zamenj', 'zamjenj'),
    ('zaplen', 'zaplijen'),
    ('zapose', 'zaposje'),
    ('zaposl', 'zapošlj'),
    ('beleg', 'biljeg'),
    ('belež', 'biljež'),
    ('celin', 'cjelin'),
    ('celog', 'cijelog'),
    ('cenit', 'cijeniti'),
    ('cveta', 'cvjeta'),
    ('decem', 'decem'),
    ('delat', 'djelat'),
    ('deleć', 'dijeleć'),
    ('delim', 'dijelim'),
    ('delić', 'djelić'),
    ('delić', 'delić'),
    ('detet', 'djetet'),
    ('devet', 'devet'),
    ('devoj', 'djevoj'),
    ('dodel', 'dodjel'),
    ('donel', 'donijel'),
    ('greja', 'grija'),
    ('greši', 'griješi'),
    ('izbeg', 'izbjeg'),
    ('izbeg', 'izbjeg'),
    ('izmen', 'izmijen'),
    ('izmer', 'izmjer'),
    ('izned', 'izned'),
    ('iznet', 'iznijet'),
    ('izveš', 'izvješ'),
    ('kolen', 'koljen'),
    ('kolev', 'kolijev'),
    ('koren', 'korijen'),
    ('lekar', 'ljekar'),
    ('lepot', 'ljepot'),
    ('lepot', 'ljepot'),
    ('letak', 'letak'),
    ('letnj', 'ljetnj'),
    ('levic', 'ljevic'),
    ('levič', 'ljevič'),
    ('mesec', 'mjesec'),
    ('namer', 'namjer'),
    ('napad', 'napad'),
    ('napad', 'napad'),
    ('nared', 'nared'),
    ('nared', 'nared'),
    ('nedel', 'nedjel'),
    ('negde', 'negdje'),
    ('nemac', 'njemac'),
    ('nemač', 'njemač'),
    ('nemoć', 'nemoć'),
    ('never', 'nevjer'),
    ('obole', 'obolje'),
    ('oceni', 'ocijeni'),
    ('ocenj', 'ocjenj'),
    ('odole', 'odolje'),
    ('opsed', 'opsjed'),
    ('oseća', 'osjeća'),
    ('osvet', 'osvjet'),
    ('pobeg', 'pobjeg'),
    ('podel', 'podijel'),
    ('podne', 'podne'),
    ('pomer', 'pomjer'),
    ('pomer', 'pomjer'),
    ('posed', 'posjed'),
    ('poset', 'posjet'),
    ('poseć', 'posjeć'),
    ('posle', 'poslije'),
    ('pover', 'povjer'),
    ('prene', 'prenije'),
    ('preti', 'prijeti'),
    ('rasej', 'rasijan'),
    ('savet', 'savjet'),
    ('sever', 'sjever'),
    ('smeja', 'smija'),
    ('smenj', 'smjenj'),
    ('smest', 'smjest'),
    ('smešt', 'smješt'),
    ('svedo', 'svjedo'),
    ('svide', 'svidje'),
    ('ubeđe', 'ubijeđe'),
    ('ucena', 'ucjena'),
    ('ucene', 'ucjene'),
    ('uceni', 'ucijeni'),
    ('ucenu', 'ucjenu'),
    ('umest', 'umjest'),
    ('usled', 'usljed'),
    ('uspeh', 'uspjeh'),
    ('uvežb', 'uvježb'),
    ('uvide', 'uvidje'),
    ('venac', 'vijenac'),
    ('veruj', 'vjeruj'),
    ('vetar', 'vjetar'),
    ('videl', 'vidjel'),
    ('volet', 'voljet'),
    ('zamen', 'zamijen'),
    ('zamer', 'zamjer'),
    ('zamer', 'zamjer'),
    ('zased', 'zasijed'),
    ('zaver', 'zavjer'),
    ('zvezd', 'zvijezd'),
    ('zvezd', 'zvjezd'),
    ('zvezd', 'zvijezd'),
    ('čovek', 'čovjek'),
    ('čoveč', 'čovječ'),
    ('želel', 'željel'),
    ('želet', 'željet'),
    ('živel', 'živjel'),
    ('živeo', 'živio'),
    ('živet', 'živjet'),
    ('žudel', 'žudel'),
    ('besn', 'bijesn'),
    ('besv', 'besvj'),
    ('beža', 'bježa'),
    ('bled', 'blijed'),
    ('breg', 'brijeg'),
    ('cena', 'cijena'),
    ('ceni', 'cijeni'),
    ('cent', 'cent'),
    ('cenu', 'cijenu'),
    ('cvet', 'cvijet'),
    ('deca', 'djeca'),
    ('deci', 'djeci'),
    ('deco', 'djeco'),
    ('decu', 'djecu'),
    ('deli', 'dijeli'),
    ('deča', 'dječa'),
    ('done', 'donije'),
    ('dvem', 'dvjem'),
    ('gnev', 'gnjev'),
    ('greh', 'grijeh'),
    ('hleb', 'hljeb'),
    ('leka', 'lijeka'),
    ('leko', 'ljeko'),
    ('leku', 'lijeku'),
    ('lenj', 'lijen'),
    ('leti', 'ljeti'),
    ('leto', 'ljeto'),
    ('letu', 'ljetu'),
    ('mese', 'mjese'),
    ('mesn', 'mjesn'),
    ('mest', 'mjest'),
    ('mlek', 'mlijek'),
    ('nemc', 'njemc'),
    ('nežn', 'nježn'),
    ('ocen', 'ocjen'),
    ('odel', 'odijel'),
    ('odel', 'odjel'),
    ('odeć', 'odjeć'),
    ('odne', 'odnije'),
    ('onde', 'ondje'),
    ('oset', 'osjet'),
    ('oseć', 'osjeć'),
    ('ovde', 'ovdje'),
    ('pesm', 'pjesm'),
    ('peva', 'pjeva'),
    ('peša', 'pješa'),
    ('peša', 'pješa'),
    ('retk', 'rijetk'),
    ('rečn', 'rječn'),
    ('reša', 'rješa'),
    ('reši', 'riješi'),
    ('seti', 'sjeti'),
    ('slep', 'slijep'),
    ('smeh', 'smijeh'),
    ('smel', 'smjel'),
    ('smer', 'smjer'),
    ('sneg', 'snijeg'),
    ('sten', 'stijen'),
    ('teme', 'tjeme'),
    ('tera', 'tjera'),
    ('tesn', 'tijesn'),
    ('ubed', 'ubijed'),
    ('ubeđ', 'ubjeđ'),
    ('unet', 'unijet'),
    ('unel', 'unijel'),
    ('uneš', 'uneš'),
    ('uspe', 'uspje'),
    ('uteh', 'utjeh'),
    ('uver', 'uvjer'),
    ('venc', 'vijenc'),
    ('venč', 'vjenč'),
    ('vero', 'vjero'),
    ('vers', 'vjers'),
    ('vest', 'vijest'),
    ('vetr', 'vjetr'),
    ('veća', 'veća'),
    ('veće', 'veće'),
    ('veći', 'veći'),
    ('vešt', 'vješt'),
    ('volj', 'volj'),
    ('vred', 'vrijed'),
    ('vređ', 'vrijeđ'),
    ('zver', 'zvijer'),
    ('žele', 'žele'),
    ('bed', 'bijed'),
    ('bel', 'bijel'),
    ('cep', 'cijep'),
    ('cev', 'cijev'),
    ('gde', 'gdje'),
    ('hte', 'htje'),
    ('lep', 'lijep'),
    ('les', 'ljes'),
    ('lev', 'lijev'),
    ('leč', 'liječ'),
    ('leš', 'lješ'),
    ('mer', 'mjer'),
    ('meš', 'mješ'),
    ('mle', 'mlje'),
    ('pes', 'pijes'),
    ('pev', 'pjev'),
    ('ređ', 'rjeđ'),
    ('reš', 'rješ'),
    ('sen', 'sjen'),
    ('seć', 'sjeć'),
    ('seć', 'sjeć'),
    ('tel', 'tijel'),
    ('vek', 'vijek'),
    ('več', 'vječ'),

]

EXACT_DICT, STEMS_DICT = {k.lower(): v for k, v in EXACT}, {k.lower(): v for k, v in STEMS}

_EX_PAT = "|".join(re.escape(k) for k in sorted(EXACT_DICT, key=len, reverse=True))
_ST_PAT = "|".join(re.escape(k) for k in sorted(STEMS_DICT, key=len, reverse=True))

_EXACT_RE = re.compile(r'(?<![^\W\d_])(' + _EX_PAT + r')(?![^\W\d_])', re.I | re.U) if EXACT_DICT else None
_STEMS_RE = re.compile(r'(?<![^\W\d_])(' + _ST_PAT + r')([^\W\d_]*)', re.I | re.U) if STEMS_DICT else None

IMENA_IZUZECI_KORIJENI = ['vera', 'veri', 'veru', 'sedić', 'seden', 'sedlar',  'slep', 'unesk']
IZUZECI_VELIKO_SLOVO = {'Nemci', 'Nemcima', 'Nemaca', 'Svetsko', 'Svetskom'}


KONTEKST_MAPE = [
    {
        'ekavski': {'sedela', 'sedeli', 'sedeo', 'sedio', 'sede', 'sedu', 'sedi', 'sedog', 'sedoh'},
        'kljucevi1': ['kos', 'brad', 'zalisc', 'star', 'godin', 'glav', 'vlas', 'obrv', 'mrsi'],
        'kljucevi2': ['stolic', 'fotelj', 'klup', 'mest', 'sto', 'sof', 'park', 'sati', 'mirn', 'prozor', 'pod', 'kuć', 'ispred'],
        'mape_grupa1': {'sedela': 'sijedila', 'sedeli': 'sijedili', 'sedeo': 'sijedio', 'sedio': 'sijedio', 'sede': 'sijede', 'sedu': 'sijedu', 'sedi': 'sijedi', 'sedog': 'sijedog', 'sedoh': 'sijedoh'},
        'mape_grupa2': {'sedela': 'sjedjela', 'sedeli': 'sjedjeli', 'sedeo': 'sjedio', 'sedio': 'sjedio', 'sede': 'sjede', 'sedu': 'sjedu', 'sedi': 'sjedi', 'sedog': 'sjedog', 'sedoh': 'sjedoh'}
    },
    {
        'ekavski': {'svet', 'sveta', 'svetu', 'svetom', 'svetovi', 'svetova', 'svetovima'},
        'kljucevi1': ['bog', 'crkv', 'otac', 'duh', 'krst', 'ikona', 'svešten', 'vjera', 'knji', 'vidi'],
        'kljucevi2': ['zemlj', 'planet', 'ljud', 'narod', 'putov', 'obid', 'držav'],
        'mape_grupa1': {'svet': 'svet', 'sveta': 'sveta', 'svetu': 'svetu', 'svetom': 'svetom', 'svetovi': 'svetovi', 'svetova': 'svetova', 'svetovima': 'svetovima'},
        'mape_grupa2': {'svet': 'svijet', 'sveta': 'svijeta', 'svetu': 'svijetu', 'svetom': 'svijetom', 'svetovi': 'svjetovi', 'svetova': 'svjetova', 'svetovima': 'svjetovima'},
    },
    {
        'ekavski': {'bela', 'bele', 'belo', 'belog', 'belom', 'belu', 'beli', 'belih', 'belim'},
        'kljucevi1': ['boj', 'papir', 'košulj', 'snijeg', 'haljin', 'zid', 'platn'],
        'kljucevi2': ['pladn', 'dan', 'zabel', 'platn', 'košulj', 'zid', 'boj'],
        'mape_grupa1': {'bela': 'bijela', 'bele': 'bijele', 'belo': 'bijelo', 'belog': 'bijelog', 'belom': 'bijelom', 'belu': 'bijelu', 'beli': 'bijeli', 'belih': 'bijelih', 'belim': 'bijelim'},
        'mape_grupa2': {'bela': 'bjelila', 'bele': 'bjelile', 'belo': 'bjelilo', 'belog': 'bjelilog', 'belom': 'bjelilom', 'belu': 'bjelilu', 'beli': 'bjelili', 'belih': 'bjelilih', 'belim': 'bjelilim'}
    },
    {
        'ekavski': {'selo', 'sela', 'selu', 'selom', 'selima'},
        'kljucevi1': ['mjest', 'mesto', 'livad', 'životinj', 'krav', 'ovc', 'babi', 'ded', 'djed', 'imanj', 'prirod', 'oranic'],
        'kljucevi2': ['stolic', 'fotelj', 'klup', 'mest', 'sto', 'sof', 'park', 'sati', 'mirn', 'prozor', 'pod', 'kuć', 'ispred', 'ptica', 'dete', 'dijete'],
        'mape_grupa1': {'selo': 'selo', 'sela': 'sela', 'selu': 'selu', 'selom': 'selom', 'selima': 'selima'},
        'mape_grupa2': {'selo': 'sjelo', 'sela': 'sjela', 'selu': 'sjelu', 'selom': 'sjelom', 'selima': 'sjelima'}
    },
    {
        'ekavski': {'dela', 'delu', 'delo', 'delima', 'delom', 'velika dela'},
        'kljucevi1': ['značajn', 'sabran', 'knjig', 'pisac', 'umetnik', 'umjetnik', 'stvor', 'autor', 'opus', 'bibliotek'],
        'kljucevi2': ['kuć', 'poslovn', 'prostor', 'imovin', 'zemljišt', 'plac', 'soba', 'sprat', 'zgrad', 'dvorišt', 'ispit'],
        'mape_grupa1': {'dela': 'djela', 'delu': 'djelu', 'delo': 'djelo', 'delima': 'djelima', 'delom': 'djelom'},
        'mape_grupa2': {'dela': 'dijela', 'delu': 'dijelu', 'delo': 'dijelo', 'delima': 'dijelovima', 'delom': 'dijelom'}
    },
    {
        'ekavski': {'veće', 'veća', 'veću', 'većim', 'većeg', 'većoj'},
        'kljucevi1': ['glomazn', 'gabarit', 'velik', 'poras', 'poveć', 'broj', 'dimenzij', 'tež', 'vis', 'šir', 'manj', 'dupl'],
        'kljucevi2': ['zasijed', 'zasjed', 'odbor', 'sudsk', 'ministarsk', 'gradsk', 'odluk', 'član', 'glasan', 'sastan', 'skupštin', 'savet', 'savjet'],
        'mape_grupa1': {'veće': 'veće', 'veća': 'veća', 'veću': 'veću', 'većim': 'većim', 'većeg': 'većeg', 'većoj': 'većoj'},
        'mape_grupa2': {'veće': 'vijeće', 'veća': 'vijeća', 'veću': 'vijeću', 'većim': 'vijećima', 'većeg': 'vijeća', 'većoj': 'vijeću'}
    },
    {
        'ekavski': {'primene', 'primena', 'primeni', 'primenu', 'primenom', 'primenama'},
        'kljucevi1': ['znanj', 'teorij', 'praks', 'metod', 'zakon', 'pravil', 'sistem', 'funkcij', 'rezultat'],
        'kljucevi2': ['alat', 'oruđ', 'kupil', 'sprem', 'priprem', 'planir', 'kazn', 'mjer', 'mjere', 'sankcij'],
        'mape_grupa1': {'primene': 'primjene', 'primena': 'primjena', 'primeni': 'primjeni', 'primenu': 'primjenu', 'primenom': 'primjenom', 'primenama': 'primjenama'},
        'mape_grupa2': {'primene': 'primijene', 'primena': 'primijene', 'primeni': 'primijene', 'primenu': 'primijene', 'primenom': 'primijene', 'primenama': 'primijene'}
    },
    {
        'ekavski': {'reci', 'recima'},
        'kljucevi1': ['nekom', 'tati', 'bratu', 'prijatelj', 'kaž', 'rekn', 'istinu', 'poruk', 'pism', 'glasn', 'tiho'],
        'kljucevi2': ['približ', 'obali', 'vod', 'tok', 'most', 'pliv', 'brod', 'čam', 'rib', 'jezer', 'mor', 'morsk'],
        'mape_grupa1': {'reci': 'reci', 'recima': 'recima'},
        'mape_grupa2': {'reci': 'rijeci', 'recima': 'riječima'}
    },
    {
        'ekavski': {'preko', 'preka', 'preke', 'preku', 'preki', 'prekog', 'prekom'},
        'kljucevi1': ['ljut', 'pogled', 'mrštit', 'osion', 'gled', 'izraz', 'oko', 'reč', 'riječ', 'narav', 'gnev', 'gnijev', 'prekor', 'hladn'],
        'kljucevi2': ['preć', 'stić', 'doć', 'zakorač', 'most', 'prug', 'šin', 'put', 'ulic', 'rijek', 'potok', 'strana', 'obala', 'granic', 'objav', 'potrebn'],
        'mape_grupa1': {'preko': 'prijeko', 'preka': 'prijeka', 'preke': 'prijeke', 'preku': 'prijeku', 'preki': 'prijeki', 'prekog': 'prijekog', 'prekom': 'prijekom'},
        'mape_grupa2': {'preko': 'preko', 'preka': 'preka', 'preke': 'preke', 'preku': 'preku', 'preki': 'preki', 'prekog': 'prekog', 'prekom': 'prekom'}
    },
    {
        'ekavski': {'slede', 'sledi', 'slediti', 'sledile', 'sledila', 'sledilo', 'sledili'},
        'kljucevi1': ['primjer', 'uputstv', 'pravil', 'savjet', 'savet', 'korak', 'trag', 'put', 'vođ', 'mentor'],
        'kljucevi2': ['krv', 'strah', 'užas', 'šok', 'hladnoć', 'mraz', 'led', 'pogled'],
        'mape_grupa1': {'slede': 'slijede', 'sledi': 'slijedi', 'slediti': 'slijediti', 'sledile': 'slijedile', 'sledila': 'slijedila', 'sledilo': 'slijedilo', 'sledili': 'slijedili'},
        'mape_grupa2': {'slede': 'slede', 'sledi': 'sledi', 'slediti': 'slediti', 'sledila': 'sledila', 'sledilo': 'sledilo', 'sledili': 'sledili'}
    },
    {
        'ekavski': {'sledeća', 'sledeći', 'sledeće', 'sledeću', 'sledećih', 'sledećem', 'sledećog', 'sledećima'},
        'kljucevi1': ['primjer', 'uputstv', 'pravil', 'savjet', 'savet', 'korak', 'trag', 'put', 'vođ', 'mentor'],
        'kljucevi2': ['pacijent', 'bolesnik', 'kandidat', 'učenik', 'kupac', 'gost', 'putnik', 'čovjek', 'čovek', 'voz', 'autobus', 'let', 'polazak', 'tokom'],
        'mape_grupa1': {'sledeća': 'slijedeća', 'sledeći': 'slijedeći', 'sledeće': 'slijedeće', 'sledeću': 'slijedeću', 'sledećih': 'slijedećih', 'sledećem': 'slijedećem', 'sledećog': 'slijedećeg', 'sledećima': 'slijedećima'},
        'mape_grupa2': {'sledeća': 'sljedeća', 'sledeći': 'sljedeći', 'sledeće': 'sljedeće', 'sledeću': 'sljedeću', 'sledećih': 'sljedećih', 'sledećem': 'sljedećem', 'sledećog': 'sljedećem', 'sledećima': 'sljedećima'}
    }
]


def da_li_je_pocetak_recenice(t, pos):
    p = t[:pos].strip()
    return not p or p[-1] in {'.', '!', '?', '\n', '"', '„', '(', '['}

def _sacuvaj_velika_slova(izv, zam, suf=""):
    if izv.isupper(): return zam.upper() + suf.upper()
    return zam.capitalize() + suf if izv.istitle() else zam + suf

def _primijeni_exact(tekst):
    if not _EXACT_RE: return tekst
    def _r(m):
        s, s_low = m.group(1), m.group(1).lower()
        is_start = da_li_je_pocetak_recenice(tekst, m.start())
        if is_start and any(s_low.startswith(k) for k in IMENA_IZUZECI_KORIJENI): return m.group(0)
        return m.group(0) if (s[0].isupper() and not is_start) else _sacuvaj_velika_slova(s, EXACT_DICT[s_low])
    return _EXACT_RE.sub(_r, tekst)

def _primijeni_stems(tekst):
    if not _STEMS_RE: return tekst
    T_IMENA, K_PREZ, T_IZUZ = {'vera', 'veri', 'veru'}, ['sedić', 'seden', 'sedlar', 'razbolović', 'slepčević'], ['telefon', 'televiz', 'telegram', 'telefons', 'televizij', 'teleskop']
    def _r(m):
        s, suf = m.group(1), m.group(2)
        s_low = s.lower()
        puna = (s + suf).lower()
        is_start = da_li_je_pocetak_recenice(tekst, m.start())
        if (is_start and (puna in T_IMENA or any(puna.startswith(k) for k in K_PREZ))) or any(puna.startswith(i) for i in T_IZUZ): return m.group(0)
        if s.isupper() and not is_start and (s + suf) in IZUZECI_VELIKO_SLOVO: return m.group(0)
        return _sacuvaj_velika_slova(s, STEMS_DICT[s_low], suf)
    return _STEMS_RE.sub(_r, tekst)

def _primijeni_kontekst_prozor(tekst):
    novi_delovi = []
    for rec in re.split(r'([.!?\n]+)', tekst):
        if not rec.strip() or re.match(r'^[...!?\n]+$', rec):
            novi_delovi.append(rec)
            continue
        tok, okol = re.split(r'([^\W\d_]+)', rec, flags=re.U), rec.lower()
        idx_p = [idx for idx, t in enumerate(tok) if re.match(r'^[^\W\d_]+$', t)]
        for i, t_idx in enumerate(idx_p):
            tr, r_low = tok[t_idx], tok[t_idx].lower()
            if i == 0 and any(r_low.startswith(k) for k in IMENA_IZUZECI_KORIJENI): continue
            for m in KONTEKST_MAPE:
                if r_low in m['ekavski']:
                    baza = m['mape_grupa1'] if sum(1 for k in m['kljucevi1'] if k in okol) > sum(1 for k in m['kljucevi2'] if k in okol) else m['mape_grupa2']
                    if r_low in baza: tok[t_idx] = _sacuvaj_velika_slova(tr, baza[r_low])
        novi_delovi.append("".join(tok))
    return "".join(novi_delovi)


def cirilica_u_latinicu(tekst):
    m = {'Љ':'Lj','Њ':'Nj','Џ':'Dž','љ':'lj','њ':'nj','џ':'dž','А':'A','а':'a','Б':'B','б':'b','В':'V','в':'v','Г':'G','г':'g','Д':'D','д':'d','Ђ':'Đ','ђ':'đ','Е':'E','е':'e','Ж':'Ž','ж':'ž','З':'Z','з':'z','И':'I','и':'i','Ј':'J','ј':'j','К':'K','к':'k','Л':'L','л':'l','М':'M','м':'m','Н':'N','н':'n','О':'O','о':'o','П':'P','п':'p','Р':'R','р':'r','С':'S','с':'s','Т':'T','т':'t','Ћ':'Ć','ћ':'ć','У':'U','у':'u','Ф':'F','ф':'f','Х':'H','х':'h','Ц':'C','ц':'c','Č':'Č','č':'č','Ш':'Š','š':'š','Ч':'Č','ч':'č'}
    return "".join(m.get(c, c) for c in tekst)

def latinica_u_cirilicu(tekst):
    for lat, cir in [('lj','љ'),('nj','њ'),('dž','џ'),('Lj','Љ'),('Nj','Њ'),('Dž','Џ'),('LJ','Љ'),('NJ','Њ'),('DŽ','Џ')]: tekst = tekst.replace(lat, cir)
    m = {'A':'А','a':'а','B':'Б','b':'б','V':'В','v':'в','G':'Г','g':'г','D':'Д','d':'д','Đ':'Ђ','đ':'ђ','E':'Е','e':'е','Ž':'Ж','ž':'ж','Z':'З','z':'з','I':'И','i':'и','J':'Ј','j':'ј','K':'К','k':'к','L':'Л','l':'л','M':'М','m':'м','N':'Н','n':'н','O':'О','o':'о','P':'П','p':'п','R':'Р','r':'р','S':'С','s':'с','T':'Т','t':'т','Ć':'Ћ','ć':'ћ','У':'У','у':'у','Ф':'Ф','ф':'ф','Х':'Х','H':'Х','h':'х','C':'Ц','c':'ц','Č':'Ч','č':'ч','Š':'Ш','š':'ш','u':'у','f':'ф','F':'Ф','U':'У','j':'ј','J':'Ј'}
    return "".join(m.get(c, c) for c in tekst)



def zamijeni_rijeci(tekst):
    if not tekst: return tekst
    je_cirilica = (tekst.lstrip() or [""])[0] in set('АБВГДЂЕЖЗИЈКЛЉМНЊОПРСТЋУФХЦЧЏШабвгдђежзијклљмнњопрстћуфхцчџш')
    if je_cirilica: tekst = cirilica_u_latinicu(tekst)
    tekst_ijekavski = _primijeni_kontekst_prozor(_primijeni_stems(_primijeni_exact(tekst)))
    return latinica_u_cirilicu(tekst_ijekavski) if je_cirilica else tekst_ijekavski


@anvil.server.callable
def ijekavizuj_tekst(ulazni_tekst):
    try: return zamijeni_rijeci(ulazni_tekst) if ulazni_tekst else ""
    except Exception as e: print(f"Greška: {e}"); return ulazni_tekst
